#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "holos"
name = "Holos"
description.en = "Identity relay server for mobile Fediverse instances"
description.fr = "Serveur relais d'identité pour instances mobiles Fediverse"

version = "2026.06.20~ynh1"

maintainers = [ ]

[upstream]
license = "AGPL-3.0-only"
website = "https://holos.social/"
admindoc = "https://holos.social/how-it-works"
code = "https://codeberg.org/tom79/Holos-Relay-Server"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "700M"
ram.build = "700M"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/tom79/Holos-Relay-Server/archive/445c75c6792112213d9760453bdf0e8b5d460b14.tar.gz"
    sha256 = "2082ab30acfd8f79903299e7bd14cf4fe2cdb4c2cba9a68e423fa5c5850410cf"
    autoupdate.strategy = "latest_forgejo_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    server.default = 4000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
